### ISSUE TITLE
Bug: regex  module missing in install

### ISSUE THREAD

**Issue by berntpopp** [hassansaei/VNtyper#1]
after installation this error occures:
```bash
import regex as re
ModuleNotFoundError: No module named 'regex'
```

**Comment by hassansaei** [comment]
> after installation this error occures:
> 
> ```shell
> import regex as re
> ModuleNotFoundError: No module named 'regex'
> ```

Hello,

You can run **"python -m pip install regex"** for the version of the python you are using to run VNtyper.
