### ISSUE TITLE
Red_Zone in Kestrel_concat not defined

### ISSUE THREAD

**Issue by berntpopp** [hassansaei/VNtyper#2]
The value "Red_Zone" in th confidence column of the Kestrel_concat dataframe is never assigned or defined and only used once.
What does this do?

```python
 Kestrel_concat = Kestrel_concat[Kestrel_concat['Confidence'] != 'Red_Zone']
```

**Comment by hassansaei** [comment]
> The value "Red_Zone" in th confidence column of the Kestrel_concat dataframe is never assigned or defined and only used once. What does this do?
> 
> ```python
>  Kestrel_concat = Kestrel_concat[Kestrel_concat['Confidence'] != 'Red_Zone']
> ```

The red zone refers to variants that have been identified with a depth score (DS) below the threshold and are subsequently filtered out. In the upcoming version, which is currently in preparation, this annotation will be excluded from the script.
