### ISSUE TITLE
Feature request: review and implement SharkVNTyper method/pipeline

### ISSUE THREAD

**Issue by berntpopp** [hassansaei/VNtyper#23]
https://pubmed.ncbi.nlm.nih.gov/39325540/
https://github.com/AlgoLab/shark

This is mostly needed for benchmarking.
It can be useful if FASTQ files are only available.
Wont work for online mode as no WASM version of SHARK and upload would be too large.
Make this a module.

**Comment by hassansaei** [comment]
Installed in Mac from: https://github.com/AlgoLab/shark

./shark -r muc1_region.fa -1 FASTQ_R1.fq.gz -2 FASTQ_R2.fq.gz -o FASTQ_shark_R1.fq.gz -p FASTQ_shark_R2.fq.gz

I shared the MUC1 region in fasta format and its index (generated from ucsc.hg19.fasta). 

https://filesender.renater.fr/?s=download&token=ac9fe625-59bf-44e2-8475-e244833b49a9
