### ISSUE TITLE
Fastq as an input: error in calculating mean coverage over the VNTR region

### ISSUE THREAD

**Issue by hassansaei** [hassansaei/VNtyper#40]
Starting from the fastq file, it stocked in the coverage calculation step. No output_sliced.bam is generated to run samtools depth on it. 

samtools depth -@ 12 -r chr1:155160500-155162000 /opt/vntyper/output/NTI_NTI1129.fastq/fastq_bam_processing/output_sliced.bam > /opt/vntyper/output/NTI_NTI1129.fastq/coverage/coverage_vntr_coverage.txt

Failed to open file "/opt/vntyper/output/NTI_NTI1129.fastq/fastq_bam_processing/output_sliced.bam" : No such file or directory

command: 
docker run -w /opt/vntyper -v ~/Desktop/exomes/:/opt/vntyper/input -v ~/Desktop/exomes/:/opt/vntyper/output  vntyper:2.0.0-alpha.25 vntyper pipeline --fastq1 /opt/vntyper/input/TEST_EXOME-NTI_NTI1129_R1.fastq --fastq2 /opt/vntyper/input/TEST_EXOME-NTI_NTI1129_R2.fastq --threads 12 --keep-intermediates -s NTI_NTI1129 -o /opt/vntyper/output/NTI_NTI1129

**Comment by berntpopp** [comment]
This could be related to the fact that currently the Docker file is set up without indexing the reference files.
I was planning to do this in the final stages to save build time.
I'll check if this is the case and find a solution to compute the indexes once and keep them outside of the actual container.

**Comment by hassansaei** [comment]
> This could be related to the fact that currently the Docker file is set up without indexing the reference files. I was planning to do this in the final stages to save build time. I'll check if this is the case and find a solution to compute the indexes once and keep them outside of the actual container.

I updated the Docker image without using the "--skip_index" option, and the error was resolved. Generating the indexes did not take significantly more time.

**Comment by hassansaei** [comment]
2024-12-14 12:40:22,729 - root - INFO - FASTQ quality control completed.
2024-12-14 12:40:22,729 - root - INFO - Calculating mean coverage over the VNTR region.

The alignment step was not explicitly defined before calculating the mean coverage. I have added a condition to ensure that coverage calculation begins only when a BAM or CRAM file is provided and bypassed this error. If a FASTQ file is supplied, I prefer to perform the alignment after completing the QC step.

**Comment by hassansaei** [comment]
I added a mapping step after the qc stage and treated the resulting alignment file similarly to the BAM input. This includes coverage calculation, slicing, indexing, and report generation. The alignment step has been removed from the adVNTR genotyping section to streamline the workflow.
