### ISSUE TITLE
Kestrel upgrade: Upgrade is not recommended and could possibly be problematic

### ISSUE THREAD

**Issue by hassansaei** [hassansaei/VNtyper#52]
The pipeline is built on Kestrel version 1.0.1, and updating to the latest version could impact the results. Therefore, upgrading without thorough performance testing is not recommended.

To ensure consistent variant-calling performance, we should compare the VCF outputs from both versions.

**Comment by berntpopp** [comment]
1.0.3 is just a documentation change.
1.0.2 has some code changes but from the version number, it just looks like bugfix.

**Comment by berntpopp** [comment]
Relates to #50
