### ISSUE TITLE
Bug(docker): Reference folder issue Genome Files and their Indexes for BWA

### ISSUE THREAD

**Issue by hassansaei** [hassansaei/VNtyper#54]
The install_references script creates a reference directory, within which it generates an alignment directory and saves the FASTA files along with their indexes. I had to update the configuration file again to make it work.

To streamline the process, we should overwrite the existing reference directory in /opt/vntyper to include the alignment directory and other ADVNTR databases, rather than creating a new references directory in the home directory.

**Comment by berntpopp** [comment]
@hassansaei : this is for Docker, right?

**Comment by hassansaei** [comment]
> @hassansaei : this is for Docker, right?

Right!

**Comment by hassansaei** [comment]
The paths for reference and index files have been corrected in install_references_config.json. All files are now properly saved in the reference directory, which already exists in /opt/vntyper/.
