### ISSUE TITLE
Docs: Explain Kestrel postprocessing heuristic better?

### ISSUE THREAD

**Issue by holtgrewe** [hassansaei/VNtyper#6]
:wave: @hassansaei @berntpopp - the V2 update is greatly appreciated as it allowed me to run this successfully.

I wonder, however, whether the heuristics around here could be explained in a better fashion?

https://github.com/hassansaei/VNtyper/blob/37f88e94e38b4089d1b5b1a7a50891a10b926245/vntyper/scripts/kestrel_genotyping.py#L491

In particular, the black magic around pandas data frame wrangling could use some polishing. IMO, we are not dealing with relevant amounts of data and explicit modeling with Python [dataclasses](https://docs.python.org/3/library/dataclasses.html) or so could make things more transparent. If you are interested, I could contribute some patches that make things more explicit without dataframes as I have been working on reproducing the method without data frames (which is now obsolete, luckily, because of your V2 updates).

**Comment by berntpopp** [comment]
Hey Manuel! Er are working on that. Let's write by mail for Carstens cohort. Best, Bernt

**Comment by berntpopp** [comment]
Thanks for the feedback and for your willingness to help make the postprocessing clearer! The relevant logic you’re referencing is indeed central to how we filter and classify Kestrel’s genotyping calls. Here’s a brief rundown:

1. **Depth Splitting & Frame Score**  
   - We parse the “Sample” column (a colon-delimited string in the VCF) to obtain the fields `Estimated_Depth_AlternateVariant` and `Estimated_Depth_Variant_ActiveRegion`.  
   - We calculate a frame score based on `(ALT_length – REF_length) / 3`, rounding to two decimals.  
   - Variants that do not produce a “frameshift” are filtered out.

2. **Depth Score**  
   - For any remaining insertion or deletion, we compute a `Depth_Score = AlternateVariant_Depth / Variant_ActiveRegion_Depth`.  
   - This ratio and other coverage thresholds (e.g., `AltDepth ≥ 20`) come from empirical/clinical validation in **Saei et al., *iScience* 26, 107171 (2023)**, showing that reads below these cutoffs risk false positives.

3. **Confidence Assignment**  
   - Based on the `Depth_Score` and coverage in the “active region,” we classify each variant into confidence categories (e.g., `Low_Precision`, `High_Precision`) using thresholds also derived from **Saei et al.** The logic is in `calculate_depth_score_and_assign_confidence()`, with conditions like:
     ```python
     if depth_score <= 0.00469 or var_region <= 200:
         return "Low_Precision"
     elif alt_depth > 100 and depth_score >= 0.00515:
         return "High_Precision*"
     ...
     ```
   - This table-like approach with “if” statements might feel “magical,” but it encodes an empirical decision tree from our validation data.

4. **Why DataFrames?**  
   - We initially used **pandas** to keep each step (filtering, merging with motifs, scoring) consistent and vectorized. This reduces boilerplate code but can obscure logic when lines like `df[~df['ALT'].isin(exclude_alts)]` appear “black-box.”  
   - While `dataclass`-based modeling would be more explicit (e.g., `VariantRecord` objects with typed attributes), our current pipeline invests heavily in these tabular transformations for speed and easy I/O. That said, we’re open to patches or design suggestions that better highlight the logic without losing too much of the convenience that DataFrames provide.

If you’re interested in contributing patches to make the postprocessing more explicit—perhaps converting the final or intermediate steps into a `VariantRecord`–like structure—we’d certainly welcome it! We think it might help new users understand the steps at a glance, particularly how the coverage thresholds and “frame shift” cutoffs play together.

Thanks again, and we appreciate your engagement and any PRs you’d like to share!
