### ISSUE TITLE
Bug: Fastp: Input contains unmatched paired reads

### ISSUE THREAD

**Issue by hassansaei** [hassansaei/VNtyper#7]
qc_command fails to generate fastq files when the input fastq paired-end files (R1 and R2) do not contain the same number of reads.

This should be solved by "-0 /dev/null" for discarding unpaired reads, "-s /dev/null" for discarding singleton reads (reads without a mate) and "-n" to ensure read names are synchronized in both files. 

[pipeline.log](https://github.com/user-attachments/files/17678656/pipeline.log)

**Comment by berntpopp** [comment]
@hassansaei : can you please provide example fastq files causing this error?

**Comment by hassansaei** [comment]
This issue is solved.
